# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
